"""Differential harness (migration spec S5): 1.4-on-PyPI vs the working
tree over the corpus. Every diff must classify against
expected_since_1.4.0.toml or the run fails.

    uv run python tools/differential/compare.py [--corpus corpus.jsonl]
"""
import argparse
import json
import re
import subprocess
import tempfile
import tomllib
from pathlib import Path

HERE = Path(__file__).resolve().parent
FIELDS = ("title", "first", "middle", "last", "suffix", "nickname",
          "maiden")

DEFAULT_BASELINE = "2.0.0"
REPO_ROOT = HERE.parents[1]
#: The v2 API's names for the same seven roles FIELDS names in v1
#: vocabulary. Both are compared from baseline 2.0 on.
V2_FIELDS = ("title", "given", "middle", "family", "suffix", "nickname",
             "maiden")
#: The two roles the FACADE names differently from Role. Diffs from
#: both surfaces canonicalize to Role's names before classification, so
#: a ledger rule names a role once -- and names it the way the codebase
#: already does everywhere else (AGENTS.md, "canonical field order").
#: The facade's vocabulary is the one that expires, at 3.0.
_V1_TO_ROLE = {"first": "given", "last": "family"}


def _parse_version(text: str) -> tuple[int, int, int]:
    """The numeric release tuple, padded to three parts. Every version
    comparison in this file goes through it.

    Explicit because string comparison is wrong twice over here: it
    orders '1.4.0' < '2.0.0' by luck and would misorder a future
    '10.0.0', and it would call a requested '2.0' unequal to a wheel
    reporting '2.0.0' -- turning a correct run into a spurious tell
    mismatch, which is an abort on a run that was fine.

    A prerelease segment is ignored: '2.0.0rc1' is release (2, 0, 0),
    because what is being asked is which RELEASE answered.
    """
    m = re.match(r"\s*(\d+)(?:\.(\d+))?(?:\.(\d+))?", text)
    if not m:
        raise SystemExit(
            f"cannot parse a version from {text!r}: expected a numeric "
            f"release like '2.0.0'")
    major, minor, micro = (int(p) if p else 0 for p in m.groups())
    return (major, minor, micro)


def _surfaces_for(version: str) -> frozenset[str]:
    """Which output surfaces a baseline can be compared on.

    1.4 has no v2 API, so a pre-2.0 baseline compares the facade
    alone. From 2.0 on both are compared: the v2 API is the primary
    surface for 2.x users, and its ambiguity kinds catch a change the
    field diff cannot see -- a parse that starts or stops reporting
    SEGMENTATION while every field stays byte-identical.
    """
    if _parse_version(version) >= (2, 0, 0):
        return frozenset({"facade", "v2"})
    return frozenset({"facade"})


def _allowlist_for(version: str) -> Path:
    """The ledger for a baseline, one file per baseline so each
    release's classified changes stay as history.

    A missing file is a hard error rather than an empty rule set: an
    empty set classifies nothing, so every diff reports UNEXPLAINED and
    the run reads as a catastrophic regression instead of as a missing
    file.
    """
    path = HERE / f"expected_since_{version}.toml"
    if not path.exists():
        raise SystemExit(
            f"no allowlist for baseline {version!r}: expected {path}. "
            f"Create it before running this baseline -- an absent "
            f"ledger cannot classify anything, so every diff would "
            f"report as unexplained.")
    return path


def _sorted_rules(rules: list[dict[str, object]]) -> list[dict[str, object]]:
    """Most-specific-first: a name_regex rule outranks a fields-only
    rule wherever both match, so file order stops being load-bearing.
    The sort is stable, so rules within a tier keep the order they were
    written in."""
    return sorted(rules, key=lambda r: not isinstance(r.get("name_regex"), str))


_WORKER_TEMPLATE = '''\
# /// script
# requires-python = ">=3.9"
# dependencies = ["nameparser==@@VERSION@@"]
# ///
"""GENERATED by tools/differential/compare.py -- edit the template
there, not a copy of this.

Writes a VERSION TELL as its first stdout line, then one result per
input name. The tell exists because the alternative failure is
invisible: a worker that silently resolved to the checkout answers
every query as the working tree while the run is labelled with the
baseline, so every diff vanishes and the run reports parity -- the
precise opposite of the truth.
"""
import json
import sys

import nameparser
from nameparser import HumanName

V1_FIELDS = ("title", "first", "middle", "last", "suffix", "nickname",
             "maiden")
V2_FIELDS = ("title", "given", "middle", "family", "suffix", "nickname",
             "maiden")
WANT_V2 = @@WANT_V2@@

print(json.dumps({"__version__": nameparser.__version__,
                  "__file__": nameparser.__file__}), flush=True)

if WANT_V2:
    from nameparser import parse

for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    name = json.loads(line)
    row = {"facade": {k: v or ""
                      for k, v in HumanName(name).as_dict().items()
                      if k in V1_FIELDS}}
    if WANT_V2:
        p = parse(name)
        v2 = {f: (getattr(p, f, "") or "") for f in V2_FIELDS}
        v2["_ambiguities"] = sorted(
            {a.kind.name for a in getattr(p, "ambiguities", ())})
        row["v2"] = v2
    print(json.dumps(row, ensure_ascii=False), flush=True)
'''


def _worker_source(version: str, want_v2: bool) -> str:
    """Render the worker with its dependency pin substituted.

    Sentinel replacement rather than str.format or f-strings: the
    worker body is mostly literal braces, and escaping every one of
    them is a defect waiting to happen in a file whose silent
    misbehavior is the thing this harness exists to prevent.
    """
    return (_WORKER_TEMPLATE
            .replace("@@VERSION@@", version)
            .replace("@@WANT_V2@@", "True" if want_v2 else "False"))


def _check_tell(tell: dict[str, str], version: str) -> None:
    """Abort before comparing anything if the wrong library answered.

    This is the check the README's trap sections exist for. Both halves
    matter and neither implies the other: an editable install reports
    the TREE's version, so version-only agreement proves nothing when
    the tree and the baseline share a number, while a genuine wheel at
    the wrong version passes any path check.
    """
    got = tell.get("__version__", "")
    where = tell.get("__file__", "")
    if not got or not where:
        raise SystemExit(
            f"baseline worker produced no usable version tell "
            f"({tell!r}); comparison aborted")
    if _parse_version(got) != _parse_version(version):
        raise SystemExit(
            f"baseline worker reports nameparser {got!r}, not the "
            f"requested {version!r} (loaded from {where}). See the "
            f"invocation traps in tools/differential/README.md; "
            f"comparison aborted.")
    if Path(where).resolve().is_relative_to(REPO_ROOT):
        raise SystemExit(
            f"baseline worker loaded nameparser from the CHECKOUT "
            f"({where}), so it answers as the working tree while "
            f"reporting {got!r} -- every diff would vanish and the run "
            f"would read as parity. Comparison aborted.")


def _run_worker(version: str, want_v2: bool,
                names: list[str]) -> tuple[dict[str, str], list[dict]]:
    """Run the baseline worker from a temp dir OUTSIDE the worktree.

    The placement is the safety mechanism, not plumbing. uv reads
    genuine PEP 723 metadata from a real script path, and sys.path[0]
    is the script's directory -- a temp dir holding no nameparser -- so
    the checkout cannot shadow the pinned wheel. The README notes that
    an absolute script path from outside the project is the one
    invocation variant that does not lie; this makes it the only one
    reachable.
    """
    with tempfile.TemporaryDirectory() as tmp:
        script = Path(tmp) / "baseline_worker.py"
        script.write_text(_worker_source(version, want_v2), encoding="utf-8")
        proc = subprocess.Popen(
            ["uv", "run", "--no-project", str(script)],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True,
            cwd=tmp)
        payload = "".join(json.dumps(n, ensure_ascii=False) + "\n"
                          for n in names)
        out, _ = proc.communicate(payload)
    # hard checks, not asserts: -O must not turn a crashed worker into
    # a truncated-but-green comparison
    if proc.returncode != 0:
        raise SystemExit(
            f"baseline worker exited {proc.returncode}; comparison aborted")
    lines = out.splitlines()
    if not lines:
        raise SystemExit(
            "baseline worker produced no output, not even a version "
            "tell; comparison aborted")
    tell = json.loads(lines[0])
    _check_tell(tell, version)
    results = [json.loads(x) for x in lines[1:]]
    if len(results) != len(names):
        raise SystemExit(
            f"worker returned {len(results)} results for {len(names)} "
            f"corpus names; comparison aborted")
    return tell, results


def _canonical_field(field: str) -> str:
    """A role's canonical name: Role's, not the facade's. Applied to
    diffs from BOTH surfaces, so it must be a no-op on names that are
    already canonical."""
    return _V1_TO_ROLE.get(field, field)


def _is_latin_only(name: str) -> bool:
    """Every character below U+0250 -- Latin, ASCII punctuation and
    Latin-1 accents.

    The partition is by SCRIPT OF THE INPUT, not by which issue claimed
    the diff, because the question it answers is whether a user parsing
    Western names sees any change at all. That number goes into the
    release notes.
    """
    return all(ord(ch) < 0x250 for ch in name)


def validate_rules(rules: list[dict[str, object]]) -> None:
    """Reject malformed allowlist rules LOUDLY at startup. A rule with
    neither name_regex nor fields would match every diff and shadow
    every later rule -- the harness would report false confidence,
    the exact failure it exists to prevent."""
    for i, rule in enumerate(rules):
        issue = rule.get("issue")
        if not isinstance(issue, str) or not issue:
            raise SystemExit(
                f"expected_since_1.4.0.toml rule #{i + 1} has no string "
                f"'issue': {rule!r}")
        if not isinstance(rule.get("name_regex"), str) \
                and not isinstance(rule.get("fields"), list):
            raise SystemExit(
                f"expected_since_1.4.0.toml rule #{i + 1} ({issue!r}) has "
                f"neither 'name_regex' nor 'fields' -- it would match "
                f"every diff and shadow every later rule")


def classify(name: str, diff_fields: set[str],
             rules: list[dict[str, object]]) -> str | None:
    for rule in rules:
        name_regex = rule.get("name_regex")
        if isinstance(name_regex, str) and not re.search(name_regex, name):
            continue
        fields = rule.get("fields")
        if isinstance(fields, list) and not diff_fields <= set(fields):
            continue
        return rule["issue"]  # type: ignore[return-value]
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    # Both corpora by default: they have different blind spots (see
    # build_issues_corpus.py), and one that has to be asked for by name
    # is one that stops being run.
    ap.add_argument("--corpus", action="append", metavar="PATH",
                    help="corpus file; repeatable. Defaults to every "
                         "corpus*.jsonl beside this script.")
    args = ap.parse_args()
    paths = ([Path(p) for p in args.corpus] if args.corpus
             else sorted(HERE.glob("corpus*.jsonl")))
    rules = tomllib.loads(
        (HERE / "expected_since_1.4.0.toml").read_text()).get("change", [])
    validate_rules(rules)
    # Most-specific-first: a name_regex rule outranks a fields-only rule
    # wherever both match, so file order stops being load-bearing. The
    # sort is stable, so rules within a tier keep the order they were
    # written in.
    rules.sort(key=lambda r: not isinstance(r.get("name_regex"), str))
    # A glob that matches nothing must not read as "everything passed".
    # Comparing zero names would print 0 unexplained and exit 0 -- the
    # harness's own stated nightmare (see validate_rules), and a
    # regression from the single hard-coded path this replaced, which
    # raised FileNotFoundError.
    if not paths:
        raise SystemExit(
            f"no corpus files found in {HERE}: expected corpus*.jsonl")
    per_file = {}
    corpus = []
    for path in paths:
        names = [json.loads(line)
                 for line in path.read_text().splitlines() if line.strip()]
        if not names:
            raise SystemExit(f"{path.name} is empty; comparison aborted")
        per_file[path.name] = len(names)
        corpus.extend(names)
    # dedupe across files, keeping first-seen order stable for output
    corpus = list(dict.fromkeys(corpus))
    # per-file counts, not just the total: a corpus that shrinks or
    # vanishes is only visible if its own number is printed
    print("corpora: " + ", ".join(f"{name} ({n})"
                                  for name, n in per_file.items()))

    proc = subprocess.Popen(
        ["uv", "run", "--no-project", str(HERE / "worker_v1.py")],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)
    v1_input = "".join(json.dumps(n, ensure_ascii=False) + "\n"
                        for n in corpus)
    v1_lines, _ = proc.communicate(v1_input)
    v1_results = [json.loads(line) for line in v1_lines.splitlines()]
    # hard checks, not asserts: -O must not turn a crashed worker into
    # a truncated-but-green comparison
    if proc.returncode != 0:
        raise SystemExit(
            f"worker_v1.py exited {proc.returncode}; comparison aborted")
    if len(v1_results) != len(corpus):
        raise SystemExit(
            f"worker returned {len(v1_results)} results for "
            f"{len(corpus)} corpus names; comparison aborted")

    from nameparser import HumanName  # the working tree (2.0 facade)
    by_issue: dict[str, list[str]] = {}
    unexplained: list[tuple[str, dict[str, str], dict[str, str]]] = []
    for name, old in zip(corpus, v1_results):
        new = {k: v or "" for k, v in HumanName(name).as_dict().items()}
        diff = {f for f in FIELDS if old.get(f, "") != new.get(f, "")}
        if not diff:
            continue
        issue = classify(name, diff, rules)
        if issue is None:
            unexplained.append((name, old, new))
        else:
            by_issue.setdefault(issue, []).append(name)

    print(f"corpus: {len(corpus)} names; "
          f"intentional diffs: {sum(map(len, by_issue.values()))}; "
          f"unexplained: {len(unexplained)}\n")
    for issue, names in sorted(by_issue.items()):
        print(f"## {issue} ({len(names)})")
        for n in names[:10]:
            print(f"  {n!r}")
        print()
    for name, old, new in unexplained:
        print(f"UNEXPLAINED {name!r}")
        for f in FIELDS:
            if old.get(f, "") != new.get(f, ""):
                print(f"    {f}: {old.get(f, '')!r} -> {new.get(f, '')!r}")
    return 1 if unexplained else 0


if __name__ == "__main__":
    raise SystemExit(main())
