# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test the Python package

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade "pip>=24.2" setuptools
        python -m pip install build
        python -m pip install twine
        python -m pip install --group dev
    - name: Run linter
      run: ruff check
    - name: Check types
      run: mypy
    - name: Run Tests
      run: |
        python tests.py
        python -m build --sdist
        twine check dist/*
        sphinx-build -b html docs dist/docs
